### PR TITLE
WIP: Bin to continuous curve conversion

### PR DESCRIPTION
**Pull request by RubendeBruin**
This merge-request is about converting spectra that are represented using bins to the superior definition using a curve:

image

I do not know what the proper naming is for this. I adopted "continuous curve" and "bins", but I'm open to suggestions.

It is my opinion that this should be done when importing data from, for example, wave riders. Especially when the data is later regridded or used for response calculations. But not everyone may agree. Hence a separate function and no build-in in the readers.

- A method to do this is added to spec.
- An example is added to the gallery (hope it works, I do not know how to test)
- Added some documentation. Could probably use a spell-check....
- Test functions added, coverage 100%

Ready for review / merge

### CODE REVIEW

**Comment by rafa-guedes** [comment]
Thanks for this pull request @RubendeBruin.

On your first point, wavespectra has always assumed the bins approach and I don't think it is a good idea to change the convention. I find the existing convention works well for me but I'm probably missing some specific use case. I'm not entirely sure why you say the continuous curve approach is a better approach.

When we convert the spectra using your code, the methods we to integrate the spectra give different results, e.g.:

```ipython

In [42]: dset = read_swan("/source/fork/wavespectra-octopus/tests/sample_files/swanfile.spec").isel(lon=0, lat=0, time=0, drop=True)

In [43]: ds = dset.spec.from_bins_to_continuous()

In [44]: float(dset.spec.hs())
Out[44]: 1.7187617512040405

In [45]: float(ds.spec.hs())
Out[45]: 1.7569648794981687

```

Differences are not large but they are noticeable (2% in this example). Should the calculation change for the case of continuous spectra, if so how? Another thing that would change since the peak value is difference is the value calculated for gamma, the Jonswap peak enhancement factor. I'm not sure which convention is more appropriate when calculating that.

**Comment by RubendeBruin** [comment]
Hi @rafa-guedes

First of all the hs should be conserved, but I check and scale using ```m0_cont = -np.trapz(center, efth.data, axis=-1)``` which may cause the difference.
 
Some more background on why is given in the docs: https://github.com/RubendeBruin/wavespectra/blob/bin_to_continuous/docs/spectral_energy_and_bins.rst

but it is indeed quite a tricky subject and it appears that very few people are aware that it exists.

In my opinion it is more natural to express a spectrum as a continuous function. But I'm an naval architect not an ocean wave scientist. 

The main use case for me is vessel responses. In that case you multiply a wave-spectrum with the square of a RAO (response amplitude operator) to obtain a response spectrum. This usually involves regridding either the RAO or the wave-spectrum or both. And re-gridding is easier on a continuous spectrum.
But also synthetic spectra like jonswap or ochi-hubble assume a continuous spectral shape. So theoretically one should correct for that when constructing one when using bins. Although practically this is solved by just increasing the number of bins.

Anyways,

For me it does not really matter if this is merged into wave-spectra. I trust your opinion on this. If it is not used here then I will simply include the code in the MaFreDo package instead and do the conversion there.

**Comment by rafa-guedes** [comment]
This sounds quite useful, and your documentation looks great - I'm in favour of adding it to the main library. Main thing at this stage would be the inconsistencies with the spectra integration and different results. What would you suggest around that?

**Comment by RubendeBruin** [comment]
Hi @rafa-guedes , just to let you know that I'm occupied with getting back home at the moment. Will hopefully have time and decent internet somewhere next month....

**Comment by RubendeBruin** [comment]
I'm back :-)

I've broken up the function into multiple parts.
- A function `_bins_to_continuous_single_spectrum` (currently in specarray.py) which works on a single 1D or 2D spectrum.
- A function `bins_from_frequency_grid` (utils.py) which figures out the frequency bin edges and widths based on the given frequency bin centers.

The method `from_bins_to_continuous` needs to call `_bins_to_continuous_single_spectrum` for each spectrum it contains. _I could use a bit of help on how to properly do this_. It somehow needs to loop over all dimensions other than 'dir' or 'freq'. I guess something with chunks is needed here as well.

**inconsistencies with the spectra integration and different results**

One of the reasons that the hs comes out different is because I think that the original hs calculation _may_ be incorrect, or at least different from what I'm doing in the conversion. The other reason was that I messed up something with the order of the dimensions.

For the swan test files the frequency grid is exponential. This means that the edges of the bins may not be in the middle of two midpoints but may (or may, depending on who made the file). In the conversion it is assumed that if the frequency grid is exponential then the bin-edges are exponential as well. In this case the frequency grid is follows 0.0354 * exp(0.1223*k) where k is the bin number so I assume that the edges are located at 0.0354 * exp(0.1223* ( k +/- 0.5) )

But if the bins are sufficiently small than none of this should matter too much. In this case:
- hs using dfarr and a summation -->1.719m 
- hs using exp binsizes and trapz --> 1.714m

**Comment by ryancoe** [comment]
@RubendeBruin - Thanks for starting this discussion and the [really nice explanations](https://github.com/RubendeBruin/wavespectra/blob/bin_to_continuous/docs/spectral_energy_and_bins.rst). You mention a main driver for this capability being looking at floating body responses and wanting the frequency points for the transfer function (e.g., RAO) of the device. I run into two scenarios for this:

1. **Empirical sea state data:** In this case, I get spectral densities from, e.g., an NDBC buoy, which are computed at a pre-determined set of frequency bins. If I wanted to look at a system response, I typically calculate the frequency response function at the NDBC frequency bin centers.
2. **Idealized sea state (e.g., JONSWAP, etc.):** As you note, in this case you have a continuous function describing the spectral density, so you may use a continuous transfer function to find system responses.

All that said, I do see some value in have the flexibility to generate a continuous spectrum from discrete bins. I think that this task is similar to any fitting problem, where your parametric model will always be imperfect to some degree. There are definitely a couple ways to go about it. It looks like you're using a piecewise function of linear curves, is that right?

**Comment by cmichelenstrofer** [comment]
I'll be honest, I'm not a big fan of introducing a second representation for the same quantity. If I understand correctly, the proposed method would change the value of the points such that the linearly interpolated (piecewise) continuous function has the same total energy. One issue is that the linear interpolation is but one option for fitting this. Another completely reasonable (and more consistent with how it is currently done), is to do a 're-bining', where you can still get the values of the function at interpolated points (the whole problem this is trying to solve) but instead of assuming a linear interpolation between points you assume bins with a smaller frequency spacing.  

Wave spectra already have too many different representations that lead to confusion. There's: 
* continuous/density (`m^2/freq/direction`) vs. discrete (`m^2`) 
* elevation variance (`m^2`) vs. energy (`J`) (factor of `ρg` difference). 
* frequency (`Hz`) vs radial frequency (`rad/s`) vs period (`s`), degrees vs. radians, and the [non-intuitive scaling](https://github.com/SNL-WaterPower/WecOptTool/discussions/106) required of the density function when switching between them. 

I think adding another difference, i.e. between bins  and linear interpolated values could lead to even more confusion. 

For your specific example that you pointed out, I usually do what @ryancoe mentioned, where my calculation points are set by the sea state data bins and I don't use any interpolation or re-binning. The RAOs are continuous so you can calculate those at the wave's bin locations. 

That being said, if you do think that there is sufficient necessity for this, the way you have implemented it (where it is not the default behavior, but an additional function you can optionally call) is the right way to go.

**Comment by cmichelenstrofer** [comment]
OK I can think of at least one scenario where this would be useful. My recommendation would be to have some sort of "post-processing" or "utilities" module and including this function in there. By having it as "postprocessing" instead of in the `core` module it would be less confusing. I can think of several functions/utilities that could go into a submodule like that (e.g. other interpolation options, unit changes, etc). I don't know what the new code refactoring looks like but if there is a a post-processing/utilty submodule I would recommend including this function there.

**Comment by cmichelenstrofer** [comment]
Also, the documentation does a great job of explaining the issue and implemented solution! Definitely keep that.

**Comment by RubendeBruin** [comment]
**Avoid multiple definitions**
I agree that it would be confusing to have multiple definitions and that this should be avoided. And as wavespectra is functioning fine using the "bin" definition this should not be changed.

**How and where to store continuous spectra**
I think there is a use for continuous spectra. At least I do need them.
That also means that a conversion function should not return a SpecArray. But then what to return? I could create a new class for "continuous spectra" which would also be useful for computed response spectra. But would rather not re-invent the wheel if something already exists.

**Use case**
As for the use-case: I frequently have to use multiple sources of wave-data with different formats and grids. For example
1. Synthetic spectra during engineering
2. Hindcast databases during suitability studies. Either from wavebuoys or models
3. Wavebuoy data during project lifetime
4. Weather forecasts for project execution day-to-day planning.

hence I cannot adjust the RAOs to fit all of these at the same time and re-gridding of the data is needed.

**How to proceed**
I will probably 
- close this pull request
- create a continuous spectra class. The logical place for me to store it would be in the [MaFreDo ](https://github.com/RubendeBruin/mafredo) package
- add a reader for WaveSpectra spectra with optional conversion to that class.

**Comment by rafa-guedes** [comment]
My general feel is that we should not change the existing convention adopted in wavespectra. However if it is useful to have a function or method that converts into the `continuous` convention, I see no harm in having that inside wavespectra (we have for instance some method to convert from energy density into energy).

The user would have to explicitly call the conversion method in order to have continuous spectra (we would not support the two conventions by default). The converted, continuous specarray object will have the existing methods to integrate spectra and calculate spectral stats, which should assume the bin convention. But a quick check here on hs, tp and dpm shows relatively small differences. I would not be to too keen to define and support a new class just to deal with the continuous definition though.

@RubendeBruin if you are keen to have the conversion method in wavespectra, I would have some comments:

- Your current method `from_bins_to_continuous` does not work for multi-dimensional spectra, only for a single spectrum. I get `ValueError: operands could not be broadcast together with shapes (23,) (5,0,1,36,24)`.
- For the case of the single spectrum it works, but loads the data into memory. We should make sure all methods return dask arrays when the input is also in dask.
- The function `wavespectra.utils.bins_from_frequency_grid()` can be replaced by something simpler like:
    left = self.spec.freq - self.df / 2
    right = self.spec.freq + self.df / 2
The results are very close. We could perhaps add these as property methods in SpecArray class.

**Comment by RubendeBruin** [comment]
Closing this request, functionality has been moved to wavedave: https://github.com/RubendeBruin/WaveDave where it is closer to its actual use case (interpolation).

**Pull request closed without merging**
