### PR TITLE
Argoss and orcaflex

### PR DESCRIPTION
**Pull request by RubendeBruin**
This MR adds support for

1.
Reading the argoss.csv format. This is a format used for weather forecasts containing spectral data. The function read_argoss_csv add reads the spectral data as well as the wind-data and forecasted Hs (as check)

2.
writing a single spectrum to and Orcaflex model. This used the orcaflex API and thus requires an orcaflex license. The included unit test will only be executed if an orcaflex model can be created using the API. Otherwise it will not be run but it will pass.

image

### CODE REVIEW

**Comment by RubendeBruin** [comment]
@rafa-guedes , I've created this MR based on the pure-python branch.

**Comment by rafa-guedes** [comment]
Thanks @RubendeBruin,

A couple of thoughts:

- There are some big changes introduced in master with https://github.com/wavespectra/wavespectra/pull/28, https://github.com/wavespectra/wavespectra/pull/30 will also be merged soon and introduce some other important changes. These are not incorporated into pure-python yet so it would be better to not branch the pull request from that to avoid conflicts.

- These argoss_csv example files look a lot like the [octopus](https://github.com/wavespectra/wavespectra/blob/master/tests/sample_files/octopusfile.oct) one - which we have a [writer function](https://github.com/wavespectra/wavespectra/blob/master/wavespectra/output/octopus.py) for, and a [placeholder for a reader function](https://github.com/wavespectra/wavespectra/blob/master/wavespectra/input/octopus.py) which have not been implemented yet.

So your function would fulfil this placeholder, the question is how to name it - I thought Octopus was the name for that file format (but I could be wrong). The other thing is it would be good to try and make it a bit more generic - your function can read [ARGOSS_example.csv](https://github.com/RubendeBruin/wavespectra/blob/argoss_and_orcaflex/tests/sample_files/ARGOSS_example.csv) but not the [ARGOSS_example2.csv](https://github.com/RubendeBruin/wavespectra/blob/argoss_and_orcaflex/tests/sample_files/ARGOSS_example2.csv), or the octopus example above (I didn't look at it in detail but the obvious differences between these files are the extra trailing commas in ARGOSS_example.csv]).

**Comment by RubendeBruin** [comment]
Hi @rafa-guedes 

I think the use for a pure-python branch will disappear once wave-spectra can be installed from conda-forge. Users without a compiler can then download the pre-compiled version. So I agree to rebase on master instead of pure-python.

For the name of the convention I'm not sure either. In my role as marine engineer I've been receiving these forecasts from argoss and fugro with minor differences in the definition of the units. But indeed the octopus format looks very similar. Is there a definition of the units for that format? And where does it come from?

Ideally suppliers of commercial forecasting services should just make sure that their format is supported by this package. Either by adjusting their output or by contributing a read function.

btw: the octopus file can not be read because it defines that there will be 181 records (spectra)  line4: nrecs,181 but only 5 are given.

**Comment by RubendeBruin** [comment]
@rafa-guedes 
I can only continue with this pr once wavespectra has been added to conda-forge. That (review) process it taking a bit longer than usual...

**Comment by RubendeBruin** [comment]
Split into #37 and #38

**Pull request closed without merging**
