### PR TITLE
Add reader function for octopus

### PR DESCRIPTION
**Pull request by RubendeBruin**
Octopus format (let's keep that name) stores the spectral energy per bin.

This pull request depends on the functionality added in #40 which is also included in this pr.

The example used for the writer function (already available) has a constant frequency grid.

The example files that I added and want to use for the read-function have an exponential grid. This makes determining the bin widths non-trivial but also raises question on how to interpolate the data in frequency direction if needed.

Referring to this issue: https://github.com/metocean/wavespectra/issues/24

- Used the existing octopus stub.
- Added two additional test-files

Notes:
- the existing test-file is incorrect. It lists a different number of data-records in the file-header than reported in the file.
Since the records that are present can be read I've made this a warning instead of an error. The valid portion of the file will be read.

Issue:

When saving a spectrum in octopus format and then loading it again, the original spectrum is not maintained:

- test_write_octopus_and_read:

image

### CODE REVIEW

**Comment by RubendeBruin** [comment]
Created a separate merge-request for the part that deals with the data-bins and the optional convergence.
#40 

This mr will build further on that mr.

**Comment by RubendeBruin** [comment]
@rafa-guedes 
There is an inconsistency in the conversion from spectral density to energy between the write and the read function. This causes the spectrum after subsequent save and load to be different from the original.

the write function used the dfarr for calculating the energy. The read function used the (new) core.utils.bins_from_frequency_grid which give different results on non-equidistant grids.

Otherwise ready to be merged I think

**Comment by rafa-guedes** [comment]
Hi Ruben, thanks for this and sorry for taking so long to start reviewing it.

A couple of initial thoughts:

- Do you mind maybe breaking this into two different pull requests, one for the octopus writer and another for the bins_to_continuous stuff?
- bins_to_continuous does not work for dask arrays because it does not allow for item assignment (the code breaks [here](https://github.com/RubendeBruin/wavespectra/blob/write_octopus/wavespectra/specarray.py#L410-L412)).
- Do we need the two new testing files [Argoss_example.csv](https://github.com/RubendeBruin/wavespectra/blob/write_octopus/tests/sample_files/Argoss_example.csv) and [Octopus_example.csv](https://github.com/RubendeBruin/wavespectra/blob/write_octopus/tests/sample_files/Octopus_example.csv) given there is already [octupusfile.oct](https://github.com/RubendeBruin/wavespectra/blob/write_octopus/tests/sample_files/octopusfile.oct)? If we do need them, can you make them smaller please, they are quite bigger than the other sample files in there.

Anyways if we break these we can probably merge the octopus stuff quicker and then discuss a bit more about the other stuff.

**Comment by rafa-guedes** [comment]
Ok you already opened a pull request #40 for the continuous stuff. If you can perhaps open a new one only with the octopus bit that will be great

**Comment by RubendeBruin** [comment]
Hi @rafa-guedes , I'll see what I can do. If I remember correctly the octupusfile.oct had an error in it.

**Comment by RubendeBruin** [comment]
continued as #56

**Pull request closed without merging**
